### PR TITLE
Third viz -VizDataGlobe

### PR DESCRIPTION
**Pull request by dhruv10**

### CODE REVIEW

**Comment by prastut** [comment]
@dhruv10 Why does the page do a full reload when I tweak the width/height of the tab?

**Comment by prastut** [comment]
@dhruv10 why does this branch contain commits which have nothing to do with viz3 i.e "homepage design" "fixed tooltip in viz1" "fixed tooltip design in viz3" ?

**Comment by dhruv10** [comment]
> @dhruv10 Why does the page do a full reload when I tweak the width/height of the tab?

The globe library has a bug ie. the globe disappears on resizing the window so I had refreshed the page when it's resized. It's a hack for now since diving into the problem took time and it can be prioritized for later.

**Comment by dhruv10** [comment]
> @dhruv10 why does this branch contain commits which have nothing to do with viz3 i.e "homepage design" "fixed tooltip in viz1" "fixed tooltip design in viz3" ?

Apologies for this human error, forgot to switch branches as I wanted to end the work asap.

**Pull request merged**
